# Generated by Django 3.0.4 on 2020-03-21 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDUser',
            fields=[
                ('bdc_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
                ('account_id', models.CharField(max_length=100)),
            ],
        ),
    ]
