# Generated by Django 3.0.4 on 2020-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tduser',
            name='client_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
