# Generated by Django 3.0.4 on 2020-03-22 02:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_tduser_client_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TDUser',
            new_name='TDAccount',
        ),
    ]
