# Generated by Django 3.0.4 on 2020-03-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rhaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.Stock')),
                ('instrument_id', models.CharField(max_length=100)),
            ],
        ),
    ]
