# Generated by Django 3.0.4 on 2020-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200323_2141'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockquote',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='stock__date__unique'),
        ),
    ]
