# Generated by Django 3.0.4 on 2020-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='manually_added',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
