# Generated by Django 3.0.4 on 2020-03-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_transfer_manually_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manually_added',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
