# Generated by Django 3.0.4 on 2020-03-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_order_manually_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='brokerage',
            field=models.CharField(max_length=5),
        ),
    ]
