# Generated by Django 3.0.4 on 2020-03-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200329_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brokerage',
        ),
    ]
